
# os: osx

# osx_image: xcode11.2
notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

language: python

cache: pip

services:
  - xvfb

python:
  - "3.9.1"

before_install:
  - sudo apt install libgtk-3-dev
  - sudo apt-get install python-wxgtk3.0
  - sudo apt-get install -y  libsdl2-dev

# command to install dependencies
install:
  - python3 --version
  - pip install html-testRunner
  - pip install python-interface
  - pip install ogl

# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh
